Used annotations

While hitting first time only goes to database next time its not got to database instead og go to database
it will check in the cache itself.
@EnableCaching
@Cacheable(cacheNames = {"userCache"})